// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/users/users.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetAgents(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Agents, error)
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	GetAgentsByDepartment(ctx context.Context, in *GetAgentsByDepartmentRequest, opts ...grpc.CallOption) (*Agents, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*User, error)
	AddAgent(ctx context.Context, in *AgentAddRequest, opts ...grpc.CallOption) (*Agent, error)
	UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*UpdateAgentStatusResponse, error)
	UpdateAgent(ctx context.Context, in *AgentUpdateRequest, opts ...grpc.CallOption) (*Agent, error)
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*AgentID, error)
	DeleteAgents(ctx context.Context, in *MultiAgentsDeleteRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	GetVisitors(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Visitors, error)
	GetVisitor(ctx context.Context, in *VisitorReq, opts ...grpc.CallOption) (*Visitor, error)
	VisitorExists(ctx context.Context, in *VisitorReq, opts ...grpc.CallOption) (*VisitorExistsRes, error)
	AddVisitor(ctx context.Context, in *Visitor, opts ...grpc.CallOption) (*Visitor, error)
	GetDepartments(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Departments, error)
	GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...grpc.CallOption) (*Department, error)
	AddDepartment(ctx context.Context, in *AddDepartmentRequest, opts ...grpc.CallOption) (*Department, error)
	UpdateDepartment(ctx context.Context, in *UpdateDepartmentRequest, opts ...grpc.CallOption) (*Department, error)
	UpdateDepartmentStatus(ctx context.Context, in *UpdateStatusDepartment, opts ...grpc.CallOption) (*Department, error)
	DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...grpc.CallOption) (*DepartmentID, error)
	DeleteDepartments(ctx context.Context, in *MultiDeleteRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	GetCustomer(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Customer, error)
	AddCustomerAccount(ctx context.Context, in *CustomerAccount, opts ...grpc.CallOption) (*CustomerAccount, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
	PasswordResetLinkHealth(ctx context.Context, in *PasswordResetLinkHealthRequest, opts ...grpc.CallOption) (*PasswordResetLinkHealthResponse, error)
	ChangePasswordByLink(ctx context.Context, in *PasswordChangeByLinkRequest, opts ...grpc.CallOption) (*PasswordChangeByLinkResponse, error)
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	GetInvites(ctx context.Context, in *GetInvitesRequest, opts ...grpc.CallOption) (*GetInvitesResponse, error)
	CancelInvite(ctx context.Context, in *CancelInviteRequest, opts ...grpc.CallOption) (*CancelInviteResponse, error)
	UpdateCompanyDetails(ctx context.Context, in *UpdateCompanyDetailsRequest, opts ...grpc.CallOption) (*UpdateCompanyDetailsResponse, error)
	AgentSignup(ctx context.Context, in *AgentSignupRequest, opts ...grpc.CallOption) (*AgentSignupResponse, error)
	DoesEmailExist(ctx context.Context, in *DoesEmailExistRequest, opts ...grpc.CallOption) (*DoesEmailExistResponse, error)
	DoesUserNameExist(ctx context.Context, in *DoesUserNameExistRequest, opts ...grpc.CallOption) (*DoesUserNameExistResponse, error)
	SendInstallationCodeToDev(ctx context.Context, in *SendInstallationCodeToDevRequest, opts ...grpc.CallOption) (*SendInstallationCodeToDevResponse, error)
	InviteAgents(ctx context.Context, in *InviteAgentsRequest, opts ...grpc.CallOption) (*InviteAgentsResponse, error)
	GenerateShareableLink(ctx context.Context, in *GenerateShareableLinkRequest, opts ...grpc.CallOption) (*GenerateShareableLinkResponse, error)
	IsSignupLinkValid(ctx context.Context, in *IsSignupLinkValidRequest, opts ...grpc.CallOption) (*IsSignupLinkValidResponse, error)
	GetRooms(ctx context.Context, in *GetRoomsRequest, opts ...grpc.CallOption) (*Rooms, error)
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error)
	GetPreviousRooms(ctx context.Context, in *GetPreviousRoomsRequest, opts ...grpc.CallOption) (*GetPreviousRoomsResponse, error)
	GetRoomsByUsers(ctx context.Context, in *GetRoomsByUsersRequest, opts ...grpc.CallOption) (*Rooms, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	GetSearchMessages(ctx context.Context, in *GetSearchMessagesRequest, opts ...grpc.CallOption) (*Messages, error)
	GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*GetFormResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	GetProfiles(ctx context.Context, in *GetProfilesRequest, opts ...grpc.CallOption) (*GetProfilesResponse, error)
	AddProfile(ctx context.Context, in *AddProfileRequest, opts ...grpc.CallOption) (*AddProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error)
	GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error)
	GetAccounts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Accounts, error)
	AgentPasswordReset(ctx context.Context, in *AgentPasswordResetRequest, opts ...grpc.CallOption) (*AgentPasswordResetResponse, error)
	GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountInfoResponse, error)
	AddNewsletterEmail(ctx context.Context, in *AddNewsletterEmailRequest, opts ...grpc.CallOption) (*AddNewsletterEmailResponse, error)
	DeleteNewsletterEmail(ctx context.Context, in *DeleteNewsletterEmailRequest, opts ...grpc.CallOption) (*DeleteNewsletterEmailResponse, error)
	SaveGetInTouch(ctx context.Context, in *SaveGetInTouchRequest, opts ...grpc.CallOption) (*SaveGetInTouchResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetAgents(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Agents, error) {
	out := new(Agents)
	err := c.cc.Invoke(ctx, "/users.UserService/GetAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/users.UserService/GetAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAgentsByDepartment(ctx context.Context, in *GetAgentsByDepartmentRequest, opts ...grpc.CallOption) (*Agents, error) {
	out := new(Agents)
	err := c.cc.Invoke(ctx, "/users.UserService/GetAgentsByDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/users.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/users.UserService/GetUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddAgent(ctx context.Context, in *AgentAddRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/users.UserService/AddAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*UpdateAgentStatusResponse, error) {
	out := new(UpdateAgentStatusResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/UpdateAgentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateAgent(ctx context.Context, in *AgentUpdateRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/users.UserService/UpdateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*AgentID, error) {
	out := new(AgentID)
	err := c.cc.Invoke(ctx, "/users.UserService/DeleteAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteAgents(ctx context.Context, in *MultiAgentsDeleteRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, "/users.UserService/DeleteAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetVisitors(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Visitors, error) {
	out := new(Visitors)
	err := c.cc.Invoke(ctx, "/users.UserService/GetVisitors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetVisitor(ctx context.Context, in *VisitorReq, opts ...grpc.CallOption) (*Visitor, error) {
	out := new(Visitor)
	err := c.cc.Invoke(ctx, "/users.UserService/GetVisitor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VisitorExists(ctx context.Context, in *VisitorReq, opts ...grpc.CallOption) (*VisitorExistsRes, error) {
	out := new(VisitorExistsRes)
	err := c.cc.Invoke(ctx, "/users.UserService/VisitorExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddVisitor(ctx context.Context, in *Visitor, opts ...grpc.CallOption) (*Visitor, error) {
	out := new(Visitor)
	err := c.cc.Invoke(ctx, "/users.UserService/AddVisitor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetDepartments(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Departments, error) {
	out := new(Departments)
	err := c.cc.Invoke(ctx, "/users.UserService/GetDepartments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...grpc.CallOption) (*Department, error) {
	out := new(Department)
	err := c.cc.Invoke(ctx, "/users.UserService/GetDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddDepartment(ctx context.Context, in *AddDepartmentRequest, opts ...grpc.CallOption) (*Department, error) {
	out := new(Department)
	err := c.cc.Invoke(ctx, "/users.UserService/AddDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateDepartment(ctx context.Context, in *UpdateDepartmentRequest, opts ...grpc.CallOption) (*Department, error) {
	out := new(Department)
	err := c.cc.Invoke(ctx, "/users.UserService/UpdateDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateDepartmentStatus(ctx context.Context, in *UpdateStatusDepartment, opts ...grpc.CallOption) (*Department, error) {
	out := new(Department)
	err := c.cc.Invoke(ctx, "/users.UserService/UpdateDepartmentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...grpc.CallOption) (*DepartmentID, error) {
	out := new(DepartmentID)
	err := c.cc.Invoke(ctx, "/users.UserService/DeleteDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteDepartments(ctx context.Context, in *MultiDeleteRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, "/users.UserService/DeleteDepartments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetCustomer(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, "/users.UserService/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddCustomerAccount(ctx context.Context, in *CustomerAccount, opts ...grpc.CallOption) (*CustomerAccount, error) {
	out := new(CustomerAccount)
	err := c.cc.Invoke(ctx, "/users.UserService/AddCustomerAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PasswordResetLinkHealth(ctx context.Context, in *PasswordResetLinkHealthRequest, opts ...grpc.CallOption) (*PasswordResetLinkHealthResponse, error) {
	out := new(PasswordResetLinkHealthResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/PasswordResetLinkHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangePasswordByLink(ctx context.Context, in *PasswordChangeByLinkRequest, opts ...grpc.CallOption) (*PasswordChangeByLinkResponse, error) {
	out := new(PasswordChangeByLinkResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/ChangePasswordByLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetInvites(ctx context.Context, in *GetInvitesRequest, opts ...grpc.CallOption) (*GetInvitesResponse, error) {
	out := new(GetInvitesResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/GetInvites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CancelInvite(ctx context.Context, in *CancelInviteRequest, opts ...grpc.CallOption) (*CancelInviteResponse, error) {
	out := new(CancelInviteResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/CancelInvite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateCompanyDetails(ctx context.Context, in *UpdateCompanyDetailsRequest, opts ...grpc.CallOption) (*UpdateCompanyDetailsResponse, error) {
	out := new(UpdateCompanyDetailsResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/UpdateCompanyDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AgentSignup(ctx context.Context, in *AgentSignupRequest, opts ...grpc.CallOption) (*AgentSignupResponse, error) {
	out := new(AgentSignupResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/AgentSignup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DoesEmailExist(ctx context.Context, in *DoesEmailExistRequest, opts ...grpc.CallOption) (*DoesEmailExistResponse, error) {
	out := new(DoesEmailExistResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/DoesEmailExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DoesUserNameExist(ctx context.Context, in *DoesUserNameExistRequest, opts ...grpc.CallOption) (*DoesUserNameExistResponse, error) {
	out := new(DoesUserNameExistResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/DoesUserNameExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendInstallationCodeToDev(ctx context.Context, in *SendInstallationCodeToDevRequest, opts ...grpc.CallOption) (*SendInstallationCodeToDevResponse, error) {
	out := new(SendInstallationCodeToDevResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/SendInstallationCodeToDev", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) InviteAgents(ctx context.Context, in *InviteAgentsRequest, opts ...grpc.CallOption) (*InviteAgentsResponse, error) {
	out := new(InviteAgentsResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/InviteAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GenerateShareableLink(ctx context.Context, in *GenerateShareableLinkRequest, opts ...grpc.CallOption) (*GenerateShareableLinkResponse, error) {
	out := new(GenerateShareableLinkResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/GenerateShareableLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsSignupLinkValid(ctx context.Context, in *IsSignupLinkValidRequest, opts ...grpc.CallOption) (*IsSignupLinkValidResponse, error) {
	out := new(IsSignupLinkValidResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/IsSignupLinkValid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetRooms(ctx context.Context, in *GetRoomsRequest, opts ...grpc.CallOption) (*Rooms, error) {
	out := new(Rooms)
	err := c.cc.Invoke(ctx, "/users.UserService/GetRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/users.UserService/GetRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPreviousRooms(ctx context.Context, in *GetPreviousRoomsRequest, opts ...grpc.CallOption) (*GetPreviousRoomsResponse, error) {
	out := new(GetPreviousRoomsResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/GetPreviousRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetRoomsByUsers(ctx context.Context, in *GetRoomsByUsersRequest, opts ...grpc.CallOption) (*Rooms, error) {
	out := new(Rooms)
	err := c.cc.Invoke(ctx, "/users.UserService/GetRoomsByUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/GetMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetSearchMessages(ctx context.Context, in *GetSearchMessagesRequest, opts ...grpc.CallOption) (*Messages, error) {
	out := new(Messages)
	err := c.cc.Invoke(ctx, "/users.UserService/GetSearchMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*GetFormResponse, error) {
	out := new(GetFormResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/GetForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetProfiles(ctx context.Context, in *GetProfilesRequest, opts ...grpc.CallOption) (*GetProfilesResponse, error) {
	out := new(GetProfilesResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/GetProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddProfile(ctx context.Context, in *AddProfileRequest, opts ...grpc.CallOption) (*AddProfileResponse, error) {
	out := new(AddProfileResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/AddProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error) {
	out := new(DeleteProfileResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/DeleteProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error) {
	out := new(GetNotificationsResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/GetNotifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAccounts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Accounts, error) {
	out := new(Accounts)
	err := c.cc.Invoke(ctx, "/users.UserService/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AgentPasswordReset(ctx context.Context, in *AgentPasswordResetRequest, opts ...grpc.CallOption) (*AgentPasswordResetResponse, error) {
	out := new(AgentPasswordResetResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/AgentPasswordReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountInfoResponse, error) {
	out := new(GetAccountInfoResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/GetAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddNewsletterEmail(ctx context.Context, in *AddNewsletterEmailRequest, opts ...grpc.CallOption) (*AddNewsletterEmailResponse, error) {
	out := new(AddNewsletterEmailResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/AddNewsletterEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteNewsletterEmail(ctx context.Context, in *DeleteNewsletterEmailRequest, opts ...grpc.CallOption) (*DeleteNewsletterEmailResponse, error) {
	out := new(DeleteNewsletterEmailResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/DeleteNewsletterEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SaveGetInTouch(ctx context.Context, in *SaveGetInTouchRequest, opts ...grpc.CallOption) (*SaveGetInTouchResponse, error) {
	out := new(SaveGetInTouchResponse)
	err := c.cc.Invoke(ctx, "/users.UserService/SaveGetInTouch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetAgents(context.Context, *AccountID) (*Agents, error)
	GetAgent(context.Context, *GetAgentRequest) (*Agent, error)
	GetAgentsByDepartment(context.Context, *GetAgentsByDepartmentRequest) (*Agents, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	GetUserByID(context.Context, *GetUserByIDRequest) (*User, error)
	AddAgent(context.Context, *AgentAddRequest) (*Agent, error)
	UpdateAgentStatus(context.Context, *UpdateAgentStatusRequest) (*UpdateAgentStatusResponse, error)
	UpdateAgent(context.Context, *AgentUpdateRequest) (*Agent, error)
	DeleteAgent(context.Context, *DeleteAgentRequest) (*AgentID, error)
	DeleteAgents(context.Context, *MultiAgentsDeleteRequest) (*OperationStatus, error)
	GetVisitors(context.Context, *AccountID) (*Visitors, error)
	GetVisitor(context.Context, *VisitorReq) (*Visitor, error)
	VisitorExists(context.Context, *VisitorReq) (*VisitorExistsRes, error)
	AddVisitor(context.Context, *Visitor) (*Visitor, error)
	GetDepartments(context.Context, *AccountID) (*Departments, error)
	GetDepartment(context.Context, *GetDepartmentRequest) (*Department, error)
	AddDepartment(context.Context, *AddDepartmentRequest) (*Department, error)
	UpdateDepartment(context.Context, *UpdateDepartmentRequest) (*Department, error)
	UpdateDepartmentStatus(context.Context, *UpdateStatusDepartment) (*Department, error)
	DeleteDepartment(context.Context, *DeleteDepartmentRequest) (*DepartmentID, error)
	DeleteDepartments(context.Context, *MultiDeleteRequest) (*OperationStatus, error)
	GetCustomer(context.Context, *AccountID) (*Customer, error)
	AddCustomerAccount(context.Context, *CustomerAccount) (*CustomerAccount, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	PasswordResetLinkHealth(context.Context, *PasswordResetLinkHealthRequest) (*PasswordResetLinkHealthResponse, error)
	ChangePasswordByLink(context.Context, *PasswordChangeByLinkRequest) (*PasswordChangeByLinkResponse, error)
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	GetInvites(context.Context, *GetInvitesRequest) (*GetInvitesResponse, error)
	CancelInvite(context.Context, *CancelInviteRequest) (*CancelInviteResponse, error)
	UpdateCompanyDetails(context.Context, *UpdateCompanyDetailsRequest) (*UpdateCompanyDetailsResponse, error)
	AgentSignup(context.Context, *AgentSignupRequest) (*AgentSignupResponse, error)
	DoesEmailExist(context.Context, *DoesEmailExistRequest) (*DoesEmailExistResponse, error)
	DoesUserNameExist(context.Context, *DoesUserNameExistRequest) (*DoesUserNameExistResponse, error)
	SendInstallationCodeToDev(context.Context, *SendInstallationCodeToDevRequest) (*SendInstallationCodeToDevResponse, error)
	InviteAgents(context.Context, *InviteAgentsRequest) (*InviteAgentsResponse, error)
	GenerateShareableLink(context.Context, *GenerateShareableLinkRequest) (*GenerateShareableLinkResponse, error)
	IsSignupLinkValid(context.Context, *IsSignupLinkValidRequest) (*IsSignupLinkValidResponse, error)
	GetRooms(context.Context, *GetRoomsRequest) (*Rooms, error)
	GetRoom(context.Context, *GetRoomRequest) (*Room, error)
	GetPreviousRooms(context.Context, *GetPreviousRoomsRequest) (*GetPreviousRoomsResponse, error)
	GetRoomsByUsers(context.Context, *GetRoomsByUsersRequest) (*Rooms, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	GetSearchMessages(context.Context, *GetSearchMessagesRequest) (*Messages, error)
	GetForm(context.Context, *GetFormRequest) (*GetFormResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	GetProfiles(context.Context, *GetProfilesRequest) (*GetProfilesResponse, error)
	AddProfile(context.Context, *AddProfileRequest) (*AddProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error)
	GetNotifications(context.Context, *GetNotificationsRequest) (*GetNotificationsResponse, error)
	GetAccounts(context.Context, *Empty) (*Accounts, error)
	AgentPasswordReset(context.Context, *AgentPasswordResetRequest) (*AgentPasswordResetResponse, error)
	GetAccountInfo(context.Context, *GetAccountInfoRequest) (*GetAccountInfoResponse, error)
	AddNewsletterEmail(context.Context, *AddNewsletterEmailRequest) (*AddNewsletterEmailResponse, error)
	DeleteNewsletterEmail(context.Context, *DeleteNewsletterEmailRequest) (*DeleteNewsletterEmailResponse, error)
	SaveGetInTouch(context.Context, *SaveGetInTouchRequest) (*SaveGetInTouchResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetAgents(context.Context, *AccountID) (*Agents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgents not implemented")
}
func (UnimplementedUserServiceServer) GetAgent(context.Context, *GetAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedUserServiceServer) GetAgentsByDepartment(context.Context, *GetAgentsByDepartmentRequest) (*Agents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentsByDepartment not implemented")
}
func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServiceServer) GetUserByID(context.Context, *GetUserByIDRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (UnimplementedUserServiceServer) AddAgent(context.Context, *AgentAddRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAgent not implemented")
}
func (UnimplementedUserServiceServer) UpdateAgentStatus(context.Context, *UpdateAgentStatusRequest) (*UpdateAgentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentStatus not implemented")
}
func (UnimplementedUserServiceServer) UpdateAgent(context.Context, *AgentUpdateRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedUserServiceServer) DeleteAgent(context.Context, *DeleteAgentRequest) (*AgentID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgent not implemented")
}
func (UnimplementedUserServiceServer) DeleteAgents(context.Context, *MultiAgentsDeleteRequest) (*OperationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgents not implemented")
}
func (UnimplementedUserServiceServer) GetVisitors(context.Context, *AccountID) (*Visitors, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitors not implemented")
}
func (UnimplementedUserServiceServer) GetVisitor(context.Context, *VisitorReq) (*Visitor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitor not implemented")
}
func (UnimplementedUserServiceServer) VisitorExists(context.Context, *VisitorReq) (*VisitorExistsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitorExists not implemented")
}
func (UnimplementedUserServiceServer) AddVisitor(context.Context, *Visitor) (*Visitor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVisitor not implemented")
}
func (UnimplementedUserServiceServer) GetDepartments(context.Context, *AccountID) (*Departments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartments not implemented")
}
func (UnimplementedUserServiceServer) GetDepartment(context.Context, *GetDepartmentRequest) (*Department, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartment not implemented")
}
func (UnimplementedUserServiceServer) AddDepartment(context.Context, *AddDepartmentRequest) (*Department, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDepartment not implemented")
}
func (UnimplementedUserServiceServer) UpdateDepartment(context.Context, *UpdateDepartmentRequest) (*Department, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDepartment not implemented")
}
func (UnimplementedUserServiceServer) UpdateDepartmentStatus(context.Context, *UpdateStatusDepartment) (*Department, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDepartmentStatus not implemented")
}
func (UnimplementedUserServiceServer) DeleteDepartment(context.Context, *DeleteDepartmentRequest) (*DepartmentID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDepartment not implemented")
}
func (UnimplementedUserServiceServer) DeleteDepartments(context.Context, *MultiDeleteRequest) (*OperationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDepartments not implemented")
}
func (UnimplementedUserServiceServer) GetCustomer(context.Context, *AccountID) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomer not implemented")
}
func (UnimplementedUserServiceServer) AddCustomerAccount(context.Context, *CustomerAccount) (*CustomerAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCustomerAccount not implemented")
}
func (UnimplementedUserServiceServer) ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedUserServiceServer) PasswordResetLinkHealth(context.Context, *PasswordResetLinkHealthRequest) (*PasswordResetLinkHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasswordResetLinkHealth not implemented")
}
func (UnimplementedUserServiceServer) ChangePasswordByLink(context.Context, *PasswordChangeByLinkRequest) (*PasswordChangeByLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePasswordByLink not implemented")
}
func (UnimplementedUserServiceServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedUserServiceServer) GetInvites(context.Context, *GetInvitesRequest) (*GetInvitesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvites not implemented")
}
func (UnimplementedUserServiceServer) CancelInvite(context.Context, *CancelInviteRequest) (*CancelInviteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelInvite not implemented")
}
func (UnimplementedUserServiceServer) UpdateCompanyDetails(context.Context, *UpdateCompanyDetailsRequest) (*UpdateCompanyDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompanyDetails not implemented")
}
func (UnimplementedUserServiceServer) AgentSignup(context.Context, *AgentSignupRequest) (*AgentSignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentSignup not implemented")
}
func (UnimplementedUserServiceServer) DoesEmailExist(context.Context, *DoesEmailExistRequest) (*DoesEmailExistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoesEmailExist not implemented")
}
func (UnimplementedUserServiceServer) DoesUserNameExist(context.Context, *DoesUserNameExistRequest) (*DoesUserNameExistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoesUserNameExist not implemented")
}
func (UnimplementedUserServiceServer) SendInstallationCodeToDev(context.Context, *SendInstallationCodeToDevRequest) (*SendInstallationCodeToDevResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInstallationCodeToDev not implemented")
}
func (UnimplementedUserServiceServer) InviteAgents(context.Context, *InviteAgentsRequest) (*InviteAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteAgents not implemented")
}
func (UnimplementedUserServiceServer) GenerateShareableLink(context.Context, *GenerateShareableLinkRequest) (*GenerateShareableLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateShareableLink not implemented")
}
func (UnimplementedUserServiceServer) IsSignupLinkValid(context.Context, *IsSignupLinkValidRequest) (*IsSignupLinkValidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsSignupLinkValid not implemented")
}
func (UnimplementedUserServiceServer) GetRooms(context.Context, *GetRoomsRequest) (*Rooms, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRooms not implemented")
}
func (UnimplementedUserServiceServer) GetRoom(context.Context, *GetRoomRequest) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (UnimplementedUserServiceServer) GetPreviousRooms(context.Context, *GetPreviousRoomsRequest) (*GetPreviousRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPreviousRooms not implemented")
}
func (UnimplementedUserServiceServer) GetRoomsByUsers(context.Context, *GetRoomsByUsersRequest) (*Rooms, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomsByUsers not implemented")
}
func (UnimplementedUserServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedUserServiceServer) GetSearchMessages(context.Context, *GetSearchMessagesRequest) (*Messages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearchMessages not implemented")
}
func (UnimplementedUserServiceServer) GetForm(context.Context, *GetFormRequest) (*GetFormResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForm not implemented")
}
func (UnimplementedUserServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedUserServiceServer) GetProfiles(context.Context, *GetProfilesRequest) (*GetProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfiles not implemented")
}
func (UnimplementedUserServiceServer) AddProfile(context.Context, *AddProfileRequest) (*AddProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProfile not implemented")
}
func (UnimplementedUserServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedUserServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedUserServiceServer) GetNotifications(context.Context, *GetNotificationsRequest) (*GetNotificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotifications not implemented")
}
func (UnimplementedUserServiceServer) GetAccounts(context.Context, *Empty) (*Accounts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccounts not implemented")
}
func (UnimplementedUserServiceServer) AgentPasswordReset(context.Context, *AgentPasswordResetRequest) (*AgentPasswordResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentPasswordReset not implemented")
}
func (UnimplementedUserServiceServer) GetAccountInfo(context.Context, *GetAccountInfoRequest) (*GetAccountInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountInfo not implemented")
}
func (UnimplementedUserServiceServer) AddNewsletterEmail(context.Context, *AddNewsletterEmailRequest) (*AddNewsletterEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewsletterEmail not implemented")
}
func (UnimplementedUserServiceServer) DeleteNewsletterEmail(context.Context, *DeleteNewsletterEmailRequest) (*DeleteNewsletterEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNewsletterEmail not implemented")
}
func (UnimplementedUserServiceServer) SaveGetInTouch(context.Context, *SaveGetInTouchRequest) (*SaveGetInTouchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveGetInTouch not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAgents(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAgentsByDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentsByDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAgentsByDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetAgentsByDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAgentsByDepartment(ctx, req.(*GetAgentsByDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByID(ctx, req.(*GetUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/AddAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddAgent(ctx, req.(*AgentAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/UpdateAgentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateAgentStatus(ctx, req.(*UpdateAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/UpdateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateAgent(ctx, req.(*AgentUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/DeleteAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiAgentsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/DeleteAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteAgents(ctx, req.(*MultiAgentsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetVisitors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetVisitors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetVisitors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetVisitors(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetVisitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetVisitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetVisitor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetVisitor(ctx, req.(*VisitorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VisitorExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VisitorExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/VisitorExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VisitorExists(ctx, req.(*VisitorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddVisitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Visitor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddVisitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/AddVisitor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddVisitor(ctx, req.(*Visitor))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetDepartments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetDepartments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetDepartments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetDepartments(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetDepartment(ctx, req.(*GetDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/AddDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddDepartment(ctx, req.(*AddDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/UpdateDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateDepartment(ctx, req.(*UpdateDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateDepartmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusDepartment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateDepartmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/UpdateDepartmentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateDepartmentStatus(ctx, req.(*UpdateStatusDepartment))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/DeleteDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteDepartment(ctx, req.(*DeleteDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteDepartments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteDepartments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/DeleteDepartments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteDepartments(ctx, req.(*MultiDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetCustomer(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddCustomerAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddCustomerAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/AddCustomerAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddCustomerAccount(ctx, req.(*CustomerAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PasswordResetLinkHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordResetLinkHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PasswordResetLinkHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/PasswordResetLinkHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PasswordResetLinkHealth(ctx, req.(*PasswordResetLinkHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePasswordByLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordChangeByLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangePasswordByLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/ChangePasswordByLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangePasswordByLink(ctx, req.(*PasswordChangeByLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetInvites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetInvites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetInvites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetInvites(ctx, req.(*GetInvitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CancelInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CancelInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/CancelInvite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CancelInvite(ctx, req.(*CancelInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateCompanyDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateCompanyDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/UpdateCompanyDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateCompanyDetails(ctx, req.(*UpdateCompanyDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AgentSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AgentSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/AgentSignup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AgentSignup(ctx, req.(*AgentSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DoesEmailExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoesEmailExistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DoesEmailExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/DoesEmailExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DoesEmailExist(ctx, req.(*DoesEmailExistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DoesUserNameExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoesUserNameExistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DoesUserNameExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/DoesUserNameExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DoesUserNameExist(ctx, req.(*DoesUserNameExistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendInstallationCodeToDev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInstallationCodeToDevRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendInstallationCodeToDev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/SendInstallationCodeToDev",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendInstallationCodeToDev(ctx, req.(*SendInstallationCodeToDevRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_InviteAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).InviteAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/InviteAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).InviteAgents(ctx, req.(*InviteAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GenerateShareableLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateShareableLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GenerateShareableLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GenerateShareableLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GenerateShareableLink(ctx, req.(*GenerateShareableLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsSignupLinkValid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsSignupLinkValidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsSignupLinkValid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/IsSignupLinkValid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsSignupLinkValid(ctx, req.(*IsSignupLinkValidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetRooms(ctx, req.(*GetRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPreviousRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreviousRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPreviousRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetPreviousRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPreviousRooms(ctx, req.(*GetPreviousRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetRoomsByUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomsByUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetRoomsByUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetRoomsByUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetRoomsByUsers(ctx, req.(*GetRoomsByUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetSearchMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSearchMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetSearchMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetSearchMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetSearchMessages(ctx, req.(*GetSearchMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetForm(ctx, req.(*GetFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProfiles(ctx, req.(*GetProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/AddProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddProfile(ctx, req.(*AddProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/DeleteProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetNotifications(ctx, req.(*GetNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAccounts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AgentPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AgentPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/AgentPasswordReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AgentPasswordReset(ctx, req.(*AgentPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/GetAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAccountInfo(ctx, req.(*GetAccountInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddNewsletterEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewsletterEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddNewsletterEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/AddNewsletterEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddNewsletterEmail(ctx, req.(*AddNewsletterEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteNewsletterEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNewsletterEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteNewsletterEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/DeleteNewsletterEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteNewsletterEmail(ctx, req.(*DeleteNewsletterEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SaveGetInTouch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGetInTouchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SaveGetInTouch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserService/SaveGetInTouch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SaveGetInTouch(ctx, req.(*SaveGetInTouchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgents",
			Handler:    _UserService_GetAgents_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _UserService_GetAgent_Handler,
		},
		{
			MethodName: "GetAgentsByDepartment",
			Handler:    _UserService_GetAgentsByDepartment_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _UserService_GetUserByID_Handler,
		},
		{
			MethodName: "AddAgent",
			Handler:    _UserService_AddAgent_Handler,
		},
		{
			MethodName: "UpdateAgentStatus",
			Handler:    _UserService_UpdateAgentStatus_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _UserService_UpdateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _UserService_DeleteAgent_Handler,
		},
		{
			MethodName: "DeleteAgents",
			Handler:    _UserService_DeleteAgents_Handler,
		},
		{
			MethodName: "GetVisitors",
			Handler:    _UserService_GetVisitors_Handler,
		},
		{
			MethodName: "GetVisitor",
			Handler:    _UserService_GetVisitor_Handler,
		},
		{
			MethodName: "VisitorExists",
			Handler:    _UserService_VisitorExists_Handler,
		},
		{
			MethodName: "AddVisitor",
			Handler:    _UserService_AddVisitor_Handler,
		},
		{
			MethodName: "GetDepartments",
			Handler:    _UserService_GetDepartments_Handler,
		},
		{
			MethodName: "GetDepartment",
			Handler:    _UserService_GetDepartment_Handler,
		},
		{
			MethodName: "AddDepartment",
			Handler:    _UserService_AddDepartment_Handler,
		},
		{
			MethodName: "UpdateDepartment",
			Handler:    _UserService_UpdateDepartment_Handler,
		},
		{
			MethodName: "UpdateDepartmentStatus",
			Handler:    _UserService_UpdateDepartmentStatus_Handler,
		},
		{
			MethodName: "DeleteDepartment",
			Handler:    _UserService_DeleteDepartment_Handler,
		},
		{
			MethodName: "DeleteDepartments",
			Handler:    _UserService_DeleteDepartments_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _UserService_GetCustomer_Handler,
		},
		{
			MethodName: "AddCustomerAccount",
			Handler:    _UserService_AddCustomerAccount_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserService_ResetPassword_Handler,
		},
		{
			MethodName: "PasswordResetLinkHealth",
			Handler:    _UserService_PasswordResetLinkHealth_Handler,
		},
		{
			MethodName: "ChangePasswordByLink",
			Handler:    _UserService_ChangePasswordByLink_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _UserService_Signup_Handler,
		},
		{
			MethodName: "GetInvites",
			Handler:    _UserService_GetInvites_Handler,
		},
		{
			MethodName: "CancelInvite",
			Handler:    _UserService_CancelInvite_Handler,
		},
		{
			MethodName: "UpdateCompanyDetails",
			Handler:    _UserService_UpdateCompanyDetails_Handler,
		},
		{
			MethodName: "AgentSignup",
			Handler:    _UserService_AgentSignup_Handler,
		},
		{
			MethodName: "DoesEmailExist",
			Handler:    _UserService_DoesEmailExist_Handler,
		},
		{
			MethodName: "DoesUserNameExist",
			Handler:    _UserService_DoesUserNameExist_Handler,
		},
		{
			MethodName: "SendInstallationCodeToDev",
			Handler:    _UserService_SendInstallationCodeToDev_Handler,
		},
		{
			MethodName: "InviteAgents",
			Handler:    _UserService_InviteAgents_Handler,
		},
		{
			MethodName: "GenerateShareableLink",
			Handler:    _UserService_GenerateShareableLink_Handler,
		},
		{
			MethodName: "IsSignupLinkValid",
			Handler:    _UserService_IsSignupLinkValid_Handler,
		},
		{
			MethodName: "GetRooms",
			Handler:    _UserService_GetRooms_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _UserService_GetRoom_Handler,
		},
		{
			MethodName: "GetPreviousRooms",
			Handler:    _UserService_GetPreviousRooms_Handler,
		},
		{
			MethodName: "GetRoomsByUsers",
			Handler:    _UserService_GetRoomsByUsers_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _UserService_GetMessages_Handler,
		},
		{
			MethodName: "GetSearchMessages",
			Handler:    _UserService_GetSearchMessages_Handler,
		},
		{
			MethodName: "GetForm",
			Handler:    _UserService_GetForm_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _UserService_GetProfile_Handler,
		},
		{
			MethodName: "GetProfiles",
			Handler:    _UserService_GetProfiles_Handler,
		},
		{
			MethodName: "AddProfile",
			Handler:    _UserService_AddProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _UserService_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _UserService_DeleteProfile_Handler,
		},
		{
			MethodName: "GetNotifications",
			Handler:    _UserService_GetNotifications_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _UserService_GetAccounts_Handler,
		},
		{
			MethodName: "AgentPasswordReset",
			Handler:    _UserService_AgentPasswordReset_Handler,
		},
		{
			MethodName: "GetAccountInfo",
			Handler:    _UserService_GetAccountInfo_Handler,
		},
		{
			MethodName: "AddNewsletterEmail",
			Handler:    _UserService_AddNewsletterEmail_Handler,
		},
		{
			MethodName: "DeleteNewsletterEmail",
			Handler:    _UserService_DeleteNewsletterEmail_Handler,
		},
		{
			MethodName: "SaveGetInTouch",
			Handler:    _UserService_SaveGetInTouch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/users/users.proto",
}
